apiVersion: punasusi.com/v1alpha1
kind: App
metadata:
  name: cp-demo
  labels:
    app-owner: andy
spec:
  id: cp-demo
  compositionSelector:
    matchLabels:
      type: customapp
  parameters:
    namespace: cpdemo
    image: httpd:latest
    port: 80
    podSize: random
    hpaMax: 2
    hpaMin: 6
